#!/bin/bash

DIR=`dirname $0`
export PYTHONHOME=$SKA
export PYTHONPATH=$DIR:$PYTHONPATH
PERL_INLINE_DIRECTORY=`/bin/mktemp -d -t starcheck_inline.XXXXXX` || exit 1
export PERL_INLINE_DIRECTORY
perl -I ${DIR}/starcheck/src/lib ${DIR}/starcheck/src/starcheck.pl "$@"
SC_STATUS=$?
if [[ -d $PERL_INLINE_DIRECTORY && $PERL_INLINE_DIRECTORY =~ .*starcheck_inline.* ]];
then
    rm -r $PERL_INLINE_DIRECTORY
fi
exit $SC_STATUS
