#!/bin/bash

unset LD_LIBRARY_PATH
unset SYBASE
unset PYTHONPATH
eval `${SKA}/bin/flt_envs -shell sh`
export PYTHONHOME=$SKA_ARCH_OS
PERL_INLINE_DIRECTORY=`/bin/mktemp -d -t starcheck_inline.XXXXXX` || exit 1
export PERL_INLINE_DIRECTORY
STARCHECK= `python -c 'import starcheck; print(starcheck.__path__[0])'`
perl -I ${STARCHECK}/src/lib ${STARCHECK}/src/starcheck.pl -sc_data ${STARCHECK}/starcheck_data "$@"
SC_STATUS=$?
if [[ -d $PERL_INLINE_DIRECTORY && $PERL_INLINE_DIRECTORY =~ .*starcheck_inline.* ]];
then
    rm -r $PERL_INLINE_DIRECTORY
fi
exit $SC_STATUS
