#!/bin/bash

# Don't unset LD_LIBRARY_PATH and SYBASE because 'perl' below
# is no longer a wrapper
#unset LD_LIBRARY_PATH
#unset SYBASE

# Unset PYTHONPATH because custom PYTHONPATH should never be allowed
# for flight starcheck
unset PYTHONPATH

PYTHON_EXE=`which python`
PYTHON_DIR=`dirname $PYTHON_EXE`
export PYTHONHOME=`dirname $PYTHON_DIR`

# Check for skare3 perl
if [[ ! -f ${PYTHONHOME}/bin/perl ]];
then
    echo "skare3 perl not installed. conda install perl perl-ska-convert"
    exit 1
fi
# Check for perl deps
perl -e "use IO::All; use Time::DayOfYear;"
if [[ $? -ne 0 ]];
then
    echo "****"
    echo "Missing starcheck ska3 perl dependencies.  Please 'conda install perl perl-core-deps perl-ska-classic'"
    echo "****"
    exit 1
fi

PERL_INLINE_DIRECTORY=`mktemp -d -t starcheck_inline.XXXXXX` || exit 1
export PERL_INLINE_DIRECTORY
STARCHECK=`python -c 'import starcheck; print(starcheck.__path__[0])'`
perl -I ${STARCHECK}/src/lib ${STARCHECK}/src/starcheck.pl "$@"
SC_STATUS=$?
if [[ -d $PERL_INLINE_DIRECTORY && $PERL_INLINE_DIRECTORY =~ .*starcheck_inline.* ]];
then
    rm -r $PERL_INLINE_DIRECTORY
fi
exit $SC_STATUS
