#!/bin/bash

# Don't unset LD_LIBRARY_PATH and SYBASE because 'perl' below
# is no longer a wrapper
#unset LD_LIBRARY_PATH
#unset SYBASE

# Unset PYTHONPATH because custom PYTHONPATH should never be allowed
# for flight starcheck
unset PYTHONPATH
export PYTHONHOME=$SKA_ARCH_OS
PERL_INLINE_DIRECTORY=`/bin/mktemp -d -t starcheck_inline.XXXXXX` || exit 1
export PERL_INLINE_DIRECTORY
STARCHECK=`python -c 'import starcheck; print(starcheck.__path__[0])'`
perl -I ${STARCHECK}/src/lib ${STARCHECK}/src/starcheck.pl "$@"
SC_STATUS=$?
if [[ -d $PERL_INLINE_DIRECTORY && $PERL_INLINE_DIRECTORY =~ .*starcheck_inline.* ]];
then
    rm -r $PERL_INLINE_DIRECTORY
fi
exit $SC_STATUS
