#! /bin/sh

# Regression tests for starcheck

# Define the files and directories
home=$PWD
mphome=/data/mpcrit1/mplogs
log=$home/regress_log
diffs=$home/regress_diffs

TESTING_BIN=$PWD/src

# Change this to /proj/sot/ska/bin after next release
RELEASE_BIN=/proj/sot/ska/bin/  

# Remove existing log and diffs files
for file in $log $diffs
do
  if [ -w $file ]
  then
    echo "rm $file"
    rm $file
  fi
done


# JAN2105A is the first AGASC 1.6 load

# First a bunch of agasc 1.5 loads

# Go through specified loads and run test and release starcheck versions
for load in \
    2004/AUG0104/oflsa \
    2004/MAR0804/oflsc \
    2003/MAR3103/oflsc \
    2004/JAN2104/oflsa \
    2004/MAR0104/oflsb \
    2004/MAR1504/oflsa \
    2004/MAR1904/oflsa \
    2004/MAR2204/oflsb \
    2004/MAR2904/oflsc \
    2004/MAY3104/oflsc \
    2004/JUL2604/oflsa \
    2004/DEC2704/oflsb 
  do
  echo ""
  echo "***** Running starcheck on load $load *****"
  
  test=$home/regress/test/$load
  release=$home/regress/release/$load

  # Make sure we have a clean test directory
  if [ -d $test ]
  then
    echo "rm -r $test"
    rm -r $test
  fi

  echo "mkdir -p $test"
  mkdir -p $test

  echo "cd $test"
  cd $test

  # Run test version
  #
  echo "Running:   $TESTING_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
  echo "******************** (TEST) $load *******************" >> $log
  $TESTING_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log 
  # Now run current release version if not already there
  #
  if [ ! -r $release/starcheck.txt ]
  then
    echo "mkdir -p $release"
    mkdir -p $release

    echo "cd $release"
    cd $release

    echo "Running: $RELEASE_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
    echo "**** (RELEASE) $load ****" >> $log
    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load  2>&1| tee -a $log
  fi  

  # Now compare with release version

  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
  echo "********************* $load ********************" >> $diffs
  diff $test/starcheck.txt $release/starcheck.txt >> $diffs

  cd $home
done

# Then a bunch of agasc 1.6 loads

# Go through specified loads and run test and release starcheck versions
for load in \
    2005/JUL1105/oflsc \
    2005/AUG2705/oflsb \
    2005/NOV0705/oflsb \
    2005/MAR0705/oflsb \
    2006/MAR0606/oflsc \
    2006/NOV1306/oflsa \
    2006/AUG0706/oflsb
  do
  echo ""
  echo "***** Running starcheck on load $load *****"

  test=$home/regress/test/$load
  release=$home/regress/release/$load

  # Make sure we have a clean test directory
  if [ -d $test ]
  then
    echo "rm -r $test"
    rm -r $test
  fi

  echo "mkdir -p $test"
  mkdir -p $test

  echo "cd $test"
  cd $test

  # Run test version
  #
  echo "Running: $home/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
  echo "******************** (TEST) $load *******************" >> $log
  $TESTING_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log 
  # Now run current release version if not already there
  #
  if [ ! -r $release/starcheck.txt ]
  then
    echo "mkdir -p $release"
    mkdir -p $release

    echo "cd $release"
    cd $release

    echo "Running: /proj/sot/ska/perl/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
    echo "**** (RELEASE) $load ****" >> $log
    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log
  fi  


  # Now compare with release version

  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
  echo "********************* $load ********************" >> $diffs
  diff $test/starcheck.txt $release/starcheck.txt >> $diffs

  cd $home
done

# Then, a bunch of agasc 1.6 loads with the updated fid characteristics

# Go through specified loads and run test and release starcheck versions
for load in \
    2007/MAR0507/oflsa \
    2007/AUG1407/oflsa \
    2008/MAY0508/oflsa
  do
  echo ""
  echo "***** Running starcheck on load $load *****"

  test=$home/regress/test/$load
  release=$home/regress/release/$load

  # Make sure we have a clean test directory
  if [ -d $test ]
  then
    echo "rm -r $test"
    rm -r $test
  fi

  echo "mkdir -p $test"
  mkdir -p $test

  echo "cd $test"
  cd $test

  # Run test version
  #
  echo "Running: $home/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load"
  echo "******************** (TEST) $load *******************" >> $log
  $TESTING_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load 2>&1| tee -a $log 
  # Now run current release version if not already there
  #
  if [ ! -r $release/starcheck.txt ]
  then
    echo "mkdir -p $release"
    mkdir -p $release

    echo "cd $release"
    cd $release

    echo "Running: /proj/sot/ska/perl/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load"
    echo "**** (RELEASE) $load ****" >> $log
    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load 2>&1| tee -a $log
  fi  


  # Now compare with release version

  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
  echo "********************* $load ********************" >> $diffs
  diff $test/starcheck.txt $release/starcheck.txt >> $diffs

  cd $home
done



