#! /bin/sh

# Comprehensive regression tests for starcheck

RunRegression()
# Run regression tests.
# Arg 1 is the AGASC version (e.g. 1p5)
# Arg 2 is the fid characteristics name (e.g. fid_CHARACTERIS_FEB07)
{
  echo ""
  echo "***** Running starcheck on load $load *****"

  agasc=${1}
  fid_char=${2}

  test=$home/regress/test/$load
  release=$home/regress/release/$load

  # Make sure we have a clean test directory
  if [ -d $test ]
  then
    echo "rm -r $test"
    rm -r $test
  fi

  echo "mkdir -p $test"
  mkdir -p $test

  echo "cd $test"
  cd $test

  # Run test version.  Use the 'starcheck' launcher to activate the dev environment
  #
  echo "Running: $SKA/bin/starcheck -agasc $agasc -fid_char $fid_char -dir $mphome/$load"
  echo "******************** (TEST) $load *******************" >> $log
  $SKA/bin/starcheck -agasc $agasc -fid_char $fid_char -dir $mphome/$load 2>&1| tee -a $log
  perl -p -i.bak -e "s{$SKA}{$RELEASE}" $test/starcheck.txt

  # Now run current release version if not already there
  #
  if [ ! -r $release/starcheck.txt ]
  then
    echo "mkdir -p $release"
    mkdir -p $release

    echo "cd $release"
    cd $release

    echo "Running: $RELEASE/bin/starcheck.pl -agasc $agasc -fid_char $fid_char -dir $mphome/$load"
    echo "**** (RELEASE) $load ****" >> $log
    env SKA=$RELEASE PERL5LIB='' SYBASE='' $RELEASE/bin/starcheck.pl -agasc $agasc -fid_char $fid_char -dir $mphome/$load 2>&1| tee -a $log
  fi  


  # Now compare with release version

  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
  echo "********************* $load ********************" >> $diffs
  diff $test/starcheck.txt $release/starcheck.txt >> $diffs

  cd $home
}
                                                                                                                                                             

# Define the files and directories
home=$PWD
mphome=/data/mpcrit1/mplogs
log=$home/regress_log
diffs=$home/regress_diffs

RELEASE=/proj/sot/ska

if [ "$SKA" = "$RELEASE" ] ; then
  echo "Error - test bin is the same as the release bin."
  exit 1
fi

# Remove existing log and diffs files
for file in $log $diffs
do
  if [ -w $file ]
  then
    echo "rm $file"
    rm $file
  fi
done


# JAN2105A is the first AGASC 1.6 load

# First a bunch of agasc 1.5 loads

# Go through specified loads and run test and release starcheck versions
for load in \
    2004/AUG0104/oflsa \
    2004/MAR0804/oflsc \
    2003/MAR3103/oflsc \
    2004/JAN2104/oflsa \
    2004/MAR0104/oflsb \
    2004/MAR1504/oflsa \
    2004/MAR1904/oflsa \
    2004/MAR2204/oflsb \
    2004/MAR2904/oflsc \
    2004/MAY3104/oflsc \
    2004/JUL2604/oflsa \
    2004/DEC2704/oflsb 
do
   RunRegression 1p5 fid_CHARACTERIS_JUL01
done

# Then a bunch of agasc 1.6 loads

# Go through specified loads and run test and release starcheck versions
for load in \
    2005/JUL1105/oflsc \
    2005/AUG2705/oflsb \
    2005/NOV0705/oflsb \
    2005/MAR0705/oflsb \
    2006/MAR0606/oflsc \
    2006/NOV1306/oflsa \
    2006/AUG0706/oflsb
do
  RunRegression 1p6 fid_CHARACTERIS_JUL01
done

# Then, a bunch of agasc 1.6 loads with the updated fid characteristics

# Go through specified loads and run test and release starcheck versions
for load in \
    2007/MAR0507/oflsa \
    2007/AUG1407/oflsa \
    2008/MAY0508/oflsa \
    2008/AUG1808/oflsa \
    2008/SEP0108/oflsb
do
  RunRegression 1p6 fid_CHARACTERIS_FEB07
done



