#!/bin/sh

unset LD_LIBRARY_PATH
unset SYBASE
unset PYTHONPATH
SKA_bin=`dirname $0`
eval `${SKA_bin}/flt_envs -shell sh`
export PYTHONHOME=$SKA_ARCH_OS
PERL_INLINE_DIRECTORY=`/bin/mktemp -d -t starcheck_inline.XXXXXX` || exit 1
export PERL_INLINE_DIRECTORY
perl ${SKA_bin}/starcheck.pl "$@"
if [[ -d $PERL_INLINE_DIRECTORY && $PERL_INLINE_DIRECTORY =~ .*starcheck_inline.* ]];
then
    rm -r $PERL_INLINE_DIRECTORY
fi
